src/helpers/api.js
src/helpers/fetchBoard.js
src/helpers/fetchBoards.js
src/helpers/fetchDiscussion.js

Add an API module for common request code, include a cache that stores response data by request URL. Clean up some hacky code that was modifying objects by reference, which then indirectly modifies the cache. Clean up calculation of discussion counts and comment counts.

Add an API module with a request cache

---

src/css/index.css
src/helpers/fetchBoard.js
src/helpers/fetchBoards.js
src/helpers/store.js
src/site/_data/boards.js
src/site/_data/discussions.js
src/site/api/chat.njk
src/site/api/discussion.njk
src/site/api/help.njk
src/site/api/science.njk
src/site/boards/chat.njk
src/site/boards/help.njk
src/site/boards/index.njk
src/site/boards/science.njk
src/site/discussions/discussion.md

Add a plain object as a data store. Store boards and discussions, keyed by ID, as we recurse the API. Update views to use data object values for pagination.
Add some styling and additional metadata to the discussion listings.

Add a data store

---

.eleventy.js
src/site/subjects/subject.njk
src/site/tags/collections.njk
src/site/tags/discussions.njk
src/site/tags/subjects.njk
src/site/tags/tag.njk

Add `collections.taggedContent` which contains tagged subjects, discussions and collections, organised by tag. Add pages to list all tagged content by type, for a given tag, plus an overall summary page for each tag.

Add tagged collections of items

---

.eleventy.js
src/css/index.css
src/site/_includes/layouts/default.njk
src/site/discussions/discussion.md
src/site/subjects/collections.njk
src/site/subjects/subject.njk
src/site/users/collections.njk
src/site/users/comments.njk
src/site/users/user.njk

Add the `1:2` column grid for subjects and subject discussions.
Add pages with full lists for collections and subject comments.

Subject page grid and content pages

---

.eleventy.js
src/css/index.css
src/helpers/fetchBoards.js
src/site/_includes/layouts/default.njk
src/site/boards/chat.njk
src/site/boards/help.njk
src/site/boards/index.njk
src/site/boards/science.njk
src/site/discussions/discussion.md
src/site/subjects/collections.njk
src/site/subjects/subject.njk

Add the default column layout to board listings.
Add individual page headings, and remove the h1 from the default page header.
Add featured projects and tags to the global boards object.
Add featured and pinned discussions to individual board pages.

Add featured and pinned discussions

---

src/api/_data/userCollections.js
src/helpers/discussionComments.js

Read discussions from the discussions export and group by type: board, collection or subject discussion. Add collection discussions to collections after reading the collections export.
Closes #21

Add comments to collections

---

.eleventy.js
src/api/_data/userCollections.js
src/api/_data/userTags.js
src/api/templates/tag.njk
src/helpers/store.js
src/helpers/tags.js
src/site/collections/collection.njk
src/site/subjects/subject.njk
src/site/tags/collections.njk
src/site/tags/discussions.njk
src/site/tags/subjects.njk
src/site/tags/tag.njk

- Add a `userTags` object to the global data for the build (`tags` is reserved in Eleventy.)
- Refactor each tag to use lists of IDs, rather than full objects, to keep the build small.
- Remove the `taggedContent` collection from the Eleventy config.
- Restore collection tags, which were removed when we switched to using files as the data source for `userCollections`.

Treat tags as global data objects

---

src/boards/_data/users.js
src/boards/discussions/discussion.njk
src/helpers/collections.js
src/helpers/users.js
src/site/_data/users.js
src/site/userCollections/collection.njk
src/subjects/_data/users.js
src/subjects/subjects/collections.njk
src/subjects/subjects/subject.njk

User name and zooniverse ID both contain characters which make them unreliable as object keys. Key the users object by user.id and look up users by ID.
Add users to board, site and subject builds, where they are used to look up avatars.

Look up avatars by user.id

---

src/helpers/api.js

avoid the proxied connection via static nginx servers, go directly to the API

use direct path to API host

---

.eleventy.js
src/boards/discussions/discussion.njk
src/components/subjectImage.js
src/site/recent/index.njk
src/site/userCollections/collection.njk
src/site/userTags/collections.njk
src/site/userTags/discussions.njk
src/site/userTags/subjects.njk
src/site/userTags/tag.njk
src/site/users/collections.njk
src/site/users/comments.njk
src/site/users/user.njk
src/subjects/subjects/collections.njk
src/subjects/subjects/subject.njk

Add a `subjectImage` shortcode that can generate a thumbnail via our thumbnail service.
Replace all subject thumbnail images with the shortcode.
Replace thumbnails with the standard image in OpenGraph metadata.
Replaces `http://` with `https://` for all subject URLs.
Closes #18.

Use the thumbnail service for subject thumbnails

---

src/boards/_data/boards.js
src/boards/_data/discussions.js
src/boards/boards/boards.11tydata.js
src/site/_data/subjects.js
src/site/_data/userCollections.js
src/site/_data/userTags.js
src/site/userTags/userTags.11tydata.js

Template data files run once for each page in a paginated collection. We only want them to run once, to generate the initial collections (subjects, tags, discussions etc.) This moves them back into global data files for each build.

Remove local template data

---

.eleventy.js
src/boards/_includes/layouts/default.njk
src/components/pageMetadata.js
src/config/index.js
src/config/penguinwatch.js
src/config/sciencegossip.js
src/helpers/project.js
src/site/_includes/layouts/default.njk
src/subjects/_includes/layouts/default.njk
src/tags/_includes/layouts/default.njk

Add `project.domain` as a configuration option. Pass the domain to a `pageMetadata` tag, which renders page metadata for each of the default layouts.
Closes #36.

Configure the project domain

---

.eleventy.js
src/api/templates/user.njk
src/boards/boards/chat.njk
src/boards/boards/help.njk
src/boards/boards/science.njk
src/boards/discussions/discussion.njk
src/components/discussionSummary.js
src/components/featuredDiscussions.js
src/helpers/slug.js
src/helpers/users.js
src/site/recent/index.njk
src/site/userCollections/collection.njk
src/site/users/collections.njk
src/site/users/comments.njk
src/site/users/user.njk
src/subjects/subjects/collections.njk
src/subjects/subjects/subject.njk

Hide email addresses by splitting usernames on `@` and keeping the first part.
Slugify usernames in URLs and links with the `slug` filter in templates. Add a `slug` function to custom shortcodes to also slugify @-mentions and author links in the featured discussion lists.
I've also tidied up discussion summaries by moving them into a shared function.
Examples of usernames from Penguin Watch:
https://talk.penguinwatch.org/users/less*(((-greater-less/
https://talk.penguinwatch.org/users/4bellabee707/
Closes #38.

Sanitise usernames

---

.eleventy.js
src/components/markdown.js
src/config/penguinwatch.js
src/config/sciencegossip.js

Add a paired, async shortcode to render markdown text.
Get the project prefix from the projects data file.
Remove project.prefix from the initial config.

markdown shortcode

---

README.md
package.json
src/helpers/project.js

Specify the target domain when building and deploying eg.
```
yarn build talk.sciencegossip.org
yarn build:boards --serve talk.sciencegossip.org
yarn dev talk.sciencegossip.org
yarn deploy -r talk.sciencegossip.org
```
The domain name must be the last argument in the build args list, and the S3 batch uploader uses the `-r` flag to specify the remote path.
Projects are looked up by comparing the domain against `project.bucket_path` in the projects data.

Add the Talk domain as a build arg.

---

src/js/index.js

Redirect old hash fragments for subjects, collections, users and tags to the new page URLs.
On window load, look for a fragment ID in the URL and redirect:
- `#/subjects/ASC0001fet` redirects to `/subjects/ASC0001fet/`.
- `#/collections/CSCL00000p` redirects to `/collections/CSCL00000p/`.
- `#/users/PinkPimpernel` redirects to `/users/pinkpimpernel/`.
- `#/search?tags[map]=true` redirects to `/tags/map/`.

Redirect old hash fragments

---

src/components/discussionComment.js
src/helpers/roles.js

Get roles from the Ouroboros API. Add in team roles, which were [embedded in the original code](https://github.com/zooniverse/Talk/blob/2e8ad17390c1d623f1868d078379e73958ff74e4/app/models/roles.coffee#L7-L8). Show roles next to a comment author's name, with minimal styling (uppercase and smallest text size.)
See https://quenchtalk.galaxyzoo.org/boards/BGS000000f/discussions/DGS000023k/ for examples of all the team roles in a single discussion.
Closes #51.

Add roles to comments

---

src/components/pageMetadata.js
src/components/subjectImage.js
src/helpers/subjectLocation.js
src/site/userCollections/collection.11tydata.js
src/site/userCollections/collection.njk
src/site/users/comments.11tydata.js
src/site/users/comments.njk
src/site/users/user.njk
src/subjectCollections/subjects/collections.11tydata.js
src/subjectCollections/subjects/collections.njk
src/subjects/subjects/subject.11tydata.js
src/subjects/subjects/subject.njk
src/tags/userTags/collections.11tydata.js
src/tags/userTags/collections.njk
src/tags/userTags/discussions.11tydata.js
src/tags/userTags/discussions.njk
src/tags/userTags/subjects.11tydata.js
src/tags/userTags/subjects.njk
src/tags/userTags/tag.11tydata.js
src/tags/userTags/tag.njk

Add the subjectLocation helper function to `og:image` URLs and the `subjectImage` component:
- Use the first URL if location is an array.
- Replace the zooniverse-static S3 domain with static.zooniverse.org.
- Replace http:// with https://.
Closes #49.
Closes #50.

subjectLocation helper function

---

src/helpers/project.js
src/helpers/talkDomain.js

Look up talk domains for Chimp & See, Higgs Hunters, Galaxy Zoo, Radio Galaxy Zoo or Galaxy Zoo Starburst. For all other projects, I think we can safely replace 'www.' with 'talk.', in the bucket path, in order to get the talk domain.
Closes #59.

Handle talk domains correctly

---

src/components/pageMetadata.js
src/components/subjectImage.js
src/helpers/subjectLocation.js

Chimp & See stores preview images in subject.location.previews[0][0]. Use this location for thumbnails and openGraph images. Add `preload="none"` and a poster image to videos.
Closes #73.

Chimp & See preview images

---

src/components/subjectImage.js

Add subject.location.thumbnail as a possible preview location.
Ignore https://www.galaxyzoo.org when passing images to the thumbnail service.
This should fix the Galaxy Zoo images that are hosted in the `www.galaxyzoo.org` S3 bucket. https://github.com/zooniverse/Talk-archiver/issues/63#issuecomment-672963039

Add thumbnail rules for Galaxy Zoo

---

src/helpers/subjectLocation.js

Rewrite Galaxy Zoo S3 URLs to use www.galaxyzoo.org.
Here's an example.
Current URL: https://s3.amazonaws.com/www.galaxyzoo.org/subjects/standard/1237656563294994765.jpg
New URL: https://www.galaxyzoo.org/subjects/standard/1237656563294994765.jpg

use www.galaxyzoo.org for GZ subjects

---

src/helpers/collections.js
src/helpers/users.js

Store users by user ID so that we can link up comments and collections to the correct user account, even if `user.name` changed over time.
This seems to work for all projects except Space Warps, where there are two user profiles that resolve to the same URL.
```
Output conflict: multiple input files are writing to `dist/api/users/pandamonium2956.json`. Use distinct `permalink` values to resolve this conflict.
```

Key users by user ID

---

package.json
src/components/markdown.js
yarn.lock

Add `markdown-it-imsize` and replace missing whitespace in the URLs of sized images.
Fixes #87.

Markdown: support sized images
